services:
  spectrum:
    build: .
    container_name: spectrum-converter
    volumes:
      - ./public/games:/games
    working_dir: /games
    tty: true
    stdin_open: true
    command: tail -f /dev/null # Keep container running
